spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pierrotbleu?createDatabaseIfNotExist=True
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    
logging:
  level:
    root: INFO  # General logging level, change to DEBUG for detailed logs during debugging
    org.springframework: WARN  # Reducing noise from Spring's internal logs
    com.boutiquepierrotbleu: DEBUG  # Detailed logs for your application's package
  file:
    name: logs/application.log  # Store logs in a 'logs' directory with the file name 'application.log'
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{35} - %msg%n"  # Pattern for console logs
